name: Build kernel module and tools

on:
  push:
    branches:
        - "master"
  pull_request:

env:
  MODULE_VERSION: "1.0.20200908"
  TOOLS_VERSION: "1.0.20200827"
  PACKAGE_RELEASE: "1"
    
jobs:
  headers:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/fossoreslp/ubnt-build:${{ matrix.image }}
      env:
        CROSS: ${{ matrix.toolchain }}
      volumes:
        - headers:/headers

    strategy:
      matrix:
        device: [e100, e200, e300, e1000, ugw3, ugw4, ugwxg]
        version: [1, 2]
        toolchain: [mips64-octeon-linux-]
        image: [octeon-kernel]
        exclude:
          - device: ugw3
            version: 2
          - device: ugw4
            version: 2
          - device: ugwxg
            version: 2
        include:
          - device: e50
            version: 1
            toolchain: mipsel-mtk-linux-
            image: mtk-kernel
          - device: e50
            version: 2
            toolchain: mipsel-linux-gnu-
            image: mipsel-kernel
    
    steps:
      - uses: actions/checkout@v2
      - name: Build headers
        run: |
          curl -o src.tar.bz2 $(jq -r '.["${{ matrix.device }}"]["${{ matrix.version }}"]' ci/ubnt-source.json)
          tar -xf src.tar.bz2 --wildcards 'source/kernel_*' --strip-components 1
          mv kernel_* kernel.tar.gz
          tar -xf kernel.tar.gz --strip-components 1
          if [ ${{ matrix.version }} -ne 1 ]; then make ARCH=mips ubnt_er_${{ matrix.device }}_defconfig; fi;
          make -j$(nproc) ARCH=mips CROSS_COMPILE=$CROSS prepare modules_prepare
          make -j$(nproc) ARCH=mips CROSS_COMPILE=$CROSS modules #vmlinux
          cp Module.symvers .config /headers
          make mrproper
          make -j$(nproc) ARCH=mips O=/headers CROSS_COMPILE=$CROSS prepare modules_prepare scripts
          rm /headers/source /headers/Makefile
          # This is from alpine linux who in turn got it from
          # http://kernel.ubuntu.com/git/ubuntu/ubuntu-zesty.git/tree/debian/rules.d/3-binary-indep.mk
          find . -path './include/*' -prune -o -path './scripts/*' -prune -o -type f \( -name 'Makefile*' -o -name 'Kconfig*' -o -name 'Kbuild*' -o -name '*.sh' -o -name '*.pl' -o -name '*.lds' -o -name 'Platform' \) -print | cpio -pdm "/headers"
          cp -a scripts include "/headers"
          find $(find arch -name include -type d -print) -type f | cpio -pdm "/headers"
      - name: Store headers in cache
        uses: actions/cache@v2
        with:
          path: /headers
          key: ${{ matrix.device }}-${{ matrix.version }}
  
  module-prepare:
    runs-on: ubuntu-20.04
    container:
      image: buildpack-deps:focal
    
    steps:
      - uses: actions/checkout@v2
      - name: Download module source
        run: |
          curl -L -o wireguard-linux-compat-$MODULE_VERSION.tar.xz https://git.zx2c4.com/wireguard-linux-compat/snapshot/wireguard-linux-compat-$MODULE_VERSION.tar.xz
          curl -L -o wireguard-linux-compat-$MODULE_VERSION.tar.asc https://git.zx2c4.com/wireguard-linux-compat/snapshot/wireguard-linux-compat-$MODULE_VERSION.tar.asc
          unxz wireguard-linux-compat-$MODULE_VERSION.tar.xz
          gpgv --keyring ci/AB9942E6D4A4CFC3412620A749FC7012A5DE03AE.gpg wireguard-linux-compat-$MODULE_VERSION.tar.asc wireguard-linux-compat-$MODULE_VERSION.tar
          tar -xf wireguard-linux-compat-$MODULE_VERSION.tar --one-top-level=module --strip-components=1
          cd module
          sed -i 's/ --dirty//g' src/Makefile
      - name: Cache module source
        uses: actions/cache@v2
        with:
          path: module
          key: module
