name: Build docker build environments

on:
  workflow_dispatch:

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:

    runs-on: ubuntu-20.04

    strategy:
        matrix:
          image: ["/tools:mips", "/tools:mipsel", ":mipsel", ":mtk", ":octeon"]
          includes:
            - image: "/tools:mips"
              dockerfile: "DOCKERFILE-tools"
              arch: "mips"
              target: "mips-linux-musl"
            - image: "/tools:mipsel"
              dockerfile: "DOCKERFILE-tools"
              arch: "mipsel"
              target: "mipsel-linux-musl"
            - image: ":mipsel"
              dockerfile: "DOCKERFILE-mipsel"
            - image: ":mtk"
              dockerfile: "DOCKERFILE-mtk"
            - image: ":octeon"
              dockerfile: "DOCKERFILE-octeon"

    steps:
      - uses: actions/checkout@v2
      
      - name: Define registry
        run: export REGISTRY=$(echo "ghcr.io/${{ github.repository_owner }}" | tr '[A-Z]' '[a-z]')

      - name: Build image
        env:
          IMAGE: ${{ matrix.image }}
          DOCKERFILE: ${{ matrix.dockerfile }}
          ARCH: ${{ matrix.arch }}
          TARGET: ${{ matrix.target }}
        run: docker build --pull -t "$REGISTRY$IMAGE" -f ci/$DOCKERFILE .

      - name: Log into GitHub Container Registry
      # TODO: Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: docker push "$REGISTRY$IMAGE"
