name: Build UnifiOS kernel module and tools

on:
  push:
    branches:
      - "master"
      - "udm-support"
  pull_request:

env:
  MODULE_VERSION: "1.0.20210424"
  TOOLS_VERSION: "1.0.20210424"

jobs:
  prepare-buildroot:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Download buildroot-2017.11.1
        run: |
          curl -o buildroot.tar.bz2 https://buildroot.org/downloads/buildroot-2017.11.1.tar.bz2
          tar -xf buildroot.tar.bz2
      - name: Prepare buildroot-2017.11.1
        run: |
          cp unifios/buildroot-config.txt buildroot-2017.11.1/.config
          cp unifios/UDM-config.txt buildroot-2017.11.1/.
          cp unifios/kernel-versions.txt buildroot-2017.11.1/.
      - name: Copy packages
        run: cp -pr unifios/packages/* buildroot-2017.11.1/package
      - name: Patches
        run: |
          patch -p0 <unifios/patches/wireguard-packages.patch
          cp unifios/patches/0001-m4-glibc-change-work-around.patch buildroot-2017.11.1/package/m4
          cp unifios/patches/0001-bison-glibc-change-work-around.patch buildroot-2017.11.1/package/bison
          cp unifios/patches/944-mpc-relative-literal-loads-logic-in-aarch64_classify_symbol.patch buildroot-2017.11.1/package/gcc/6.4.0
      - name: Generate artifacts
        run: tar -cf buildroot.tar buildroot-2017.11.1
      - name: Store headers
        uses: actions/upload-artifact@v2
        with:
          name: buildroot
          path: buildroot.tar
  build-modules:
    needs: [prepare-buildroot]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        kernel: [-v1.9.2.3432-3f1425e, -v1.9.3.3438-50c9676, -v0.5.0-2.3464-3238f5d, -v1.9.0-1.3475-4851b2b]
    steps:
      - name: Restore buildroot
        uses: actions/download-artifact@v2
        with:
          name: buildroot
      - name: Extract buildroot
        run: tar -xf buildroot.tar
      - name: Build wireguard module
        run: |
          mkdir modules
          cd buildroot-2017.11.1
          make wireguard-linux-compat-dirclean
          sed -i -e '/CONFIG_LOCALVERSION=/s/.*/CONFIG_LOCALVERSION="'${{ matrix.kernel }}'"/' UDM-config.txt
          make wireguard-linux-compat-rebuild -j$(nproc)
          cp output/build/wireguard-linux-compat-1.0.20210219/src/wireguard.ko ../modules/wireguard-4.1.37${{ matrix.kernel }}.ko
          cp output/build/linux-custom/net/ipv4/netfilter/iptable_raw.ko ../modules/iptable_raw-4.1.37${{ matrix.kernel }}.ko
      - name: Store modules
        uses: actions/upload-artifact@v2
        with:
          name: modules
          path: modules
  build-tools:
    needs: [prepare-buildroot]
    runs-on: ubuntu-20.04
    steps:
      - name: Restore buildroot
        uses: actions/download-artifact@v2
        with:
          name: buildroot
      - name: Extract buildroot
        run: tar -xf buildroot.tar
      - name: Build WireGuard tools
        run: cd buildroot-2017.11.1 && make wireguard-tools-rebuild # -> output/target/usr/bin/wg
      - name: Build bash
        run: cd buildroot-2017.11.1 && make bash-rebuild # -> output/target/bin/bash
      - name: Move bash
        run: cp buildroot-2017.11.1/output/target/bin/bash buildroot-2017.11.1/output/target/usr/bin/
      - name: Build qrencode
        run: cd buildroot-2017.11.1 && make libqrencode-rebuild # -> output/target/usr/bin/qrencode
      - name: Build htop
        run: cd buildroot-2017.11.1 && make htop-rebuild # -> output/target/usr/bin/htop
      - name: Build iftop
        run: cd buildroot-2017.11.1 && make iftop-rebuild # -> output/target/usr/sbin/iftop
      - name: Store tools
        uses: actions/upload-artifact@v2
        with:
          name: tools
          path: buildroot-2017.11.1/output/target/usr

  package:
    needs: [build-modules, build-tools]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: mkdir package package/usr
      - name: Restore modules
        uses: actions/download-artifact@v2
        with:
          name: modules
          path: package
      - name: Restore tools
        uses: actions/download-artifact@v2
        with:
          name: tools
          path: package/usr
      - name: Add setup
        run: cp unifios/setup_wireguard.sh package/
      - name: Add wg-quick
        run: |
          curl -o package/usr/bin/wg-quick https://git.zx2c4.com/wireguard-tools/plain/src/wg-quick/linux.bash
          chmod +x package/usr/bin/wg-quick
      - name: Package
        run: tar -czf UnifiOS-$MODULE_VERSION.tar.gz package/
      - name: Store package
        uses: actions/upload-artifact@v2
        with:
          name: release_unifios
          path: UnifiOS-$MODULE_VERSION.tar.gz
